<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chris Babcock">
<meta name="dcterms.date" content="2026-04-09">

<title>Data Analysis Replication Assignment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="data-analysis-replication_files/libs/clipboard/clipboard.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="data-analysis-replication_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="data-analysis-replication_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="data-analysis-replication_files/libs/quarto-html/popper.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/anchor.min.js"></script>
<link href="data-analysis-replication_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="data-analysis-replication_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="data-analysis-replication_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="data-analysis-replication_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="data-analysis-replication_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Analysis Replication Assignment</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chris Babcock </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This paper is looking into the structural, pharmacological, and therapeutic properties of a class of serotonin receptor (5-HT) agonists called 5-methoxytryptamines (5-MeO-Ts), particularly the 5-HT1A and 5-HT2A agonist 5-methoxy-N,N-dimethyltryptamine (5-MeO-DMT). The exact structure of 5-MeO-DMT was mapped out, as well as how it fits in and affects the conformation of the 5-HT1A and 5-HT2A receptors, using cryogenic electron microscopy. Its pharmacological properties were determined using in vitro 5-HT1A and 5-HT2A receptor activity assays, and in vivo behavioral/therapeutic properties measured using wild-type mice include head twitching, sucrose preference, locomotor activity, social interaction, anxiety, and susceptibility to stress.</p>
<p>5-MeO-DMT’s properties were compared with other 5-HT receptor agonists, such as the pan-serotonergic agonist lysergic acid diethylamide (LSD), the full serotonergic agonist mescaline, clinically-used 5-HT1A agonists, and other 5-MeO-Ts. The 5-MeO-Ts, including 5-MeO-DMT, were paired with the 5-HT1A-specific antagonist WAY-100635 in some of the in vivo experiments in order to show that the compounds’ effects were due to 5-HT1A activity specifically.</p>
<p>5-MeO-DMT was found to be a full 5-HT1A agonist and a partial 5-HT2A agonist, with relatively moderate potency; This was confirmed with head twitch observation following administration of 5-MeO-DMT with and without WAY-100635. However, 4-fluoro,5-methoxy-N,N-pyrrolidinyl-tryptamine (4-F,5-MeO-PyrT), which is also a full 5-HT1A agonist but has less activity at 5-HT2A, did not seem to activate 5-HT2A to behaviorally significant levels, and it was still able to restore social interaction in socially stressed mice.</p>
<p>The larger point this paper is trying to make is that many of the therapeutic effects seen in antidepressive, antipsychotic, and anti-anxiety serotonergic medications are likely mainly attributed to their activity at the 5-HT1A receptor, not the 5-HT2A receptor (which is responsible for sensory disturbances associated with serotonergic medication); therefore, 5-HT1A-specific compounds may be the answer to alleviating these side effects.</p>
<p>I will be replicating the behavioral data in Figures 5d-e and Extended Data Figures 7d-h, since these are the only data in which statistical tests were done beyond standard error calculation.</p>
</section>
<section id="visualization-of-data" class="level2">
<h2 class="anchored" data-anchor-id="visualization-of-data">Visualization of Data</h2>
<p>First, let’s load in our essential libraries:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(tibble)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(tidyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(janitor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>## Warning: package 'janitor' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>## 
## Attaching package: 'janitor'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>## The following objects are masked from 'package:stats':
## 
##     chisq.test, fisher.test</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(car)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>## Warning: package 'car' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>## Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>## 
## Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>## The following object is masked from 'package:dplyr':
## 
##     recode</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">library</span>(agricolae)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>## Warning: package 'agricolae' was built under R version 4.5.3</code></pre>
</div>
</div>
<p>And now we can load in our data, starting with Figure 5:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Figure 5.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Figure%205.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Let’s read in the associated data tables, starting with Figure 5d:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"Fig 5"</span>, <span class="at">range =</span> <span class="st">"C23:BD27"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">col_types =</span> <span class="st">"text"</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>) <span class="co"># reads in the data table we need specifically</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">t</span>(f) <span class="co"># swaps columns with rows, so we can work with the table easier</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">row_to_names</span>(f, <span class="at">row_number =</span> <span class="dv">1</span>) <span class="co"># assigns proper names to columns</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> control <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Control"</span>, <span class="at">times =</span> <span class="dv">17</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> stress <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Stress"</span>, <span class="at">times =</span> <span class="dv">36</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> condition <span class="ot">&lt;-</span> <span class="fu">append</span>(control, <span class="at">values =</span> stress)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f[<span class="dv">1</span><span class="sc">:</span><span class="dv">53</span>] <span class="ot">=</span> condition <span class="co"># fills out missing values for stress condition</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(f, <span class="at">.name_repair =</span> <span class="st">"universal_quiet"</span>) <span class="co"># converts table to a format we can work with easier</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, Vehicle) <span class="sc">%&gt;%</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(Vehicle)) <span class="sc">%&gt;%</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Interaction.Ratio))</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f1 <span class="sc">%&gt;%</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f1))) <span class="sc">%&gt;%</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Interaction.Ratio) <span class="co"># separates all data points since each one is from a different subject, and makes an extra column that keeps track of treatment condition</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT) <span class="sc">%&gt;%</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT)) <span class="sc">%&gt;%</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Interaction.Ratio))</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f2 <span class="sc">%&gt;%</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"..4.F..5.MeO.pyrT"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f2))) <span class="sc">%&gt;%</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Interaction.Ratio)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f3 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, WAY.<span class="fl">100.635</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(WAY.<span class="fl">100.635</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Interaction.Ratio))</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f3 <span class="ot">&lt;-</span> f3 <span class="sc">%&gt;%</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY.100.635"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f3))) <span class="sc">%&gt;%</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Interaction.Ratio)</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f4 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT..WAY.<span class="fl">100.635</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT..WAY.<span class="fl">100.635</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Interaction.Ratio))</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f4 <span class="ot">&lt;-</span> f4 <span class="sc">%&gt;%</span></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"..4.F..5.MeO.pyrT..WAY.100.635"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f4))) <span class="sc">%&gt;%</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Interaction.Ratio)</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f5d <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Condition =</span> <span class="fu">character</span>(), <span class="at">Treatment =</span> <span class="fu">character</span>(), <span class="at">Interaction.Ratio =</span> <span class="fu">numeric</span>())</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f5d <span class="ot">&lt;-</span> f5d <span class="sc">%&gt;%</span> <span class="co"># combines all separate treatments into a single usable table</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f1) <span class="sc">%&gt;%</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f2) <span class="sc">%&gt;%</span></span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f3) <span class="sc">%&gt;%</span></span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f4)</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f5d))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 3
##   Condition Treatment Interaction.Ratio
##   &lt;chr&gt;     &lt;chr&gt;                 &lt;dbl&gt;
## 1 Control   Vehicle                1.48
## 2 Control   Vehicle                1.06
## 3 Control   Vehicle                1.19
## 4 Control   Vehicle                1.20
## 5 Control   Vehicle                1.26
## 6 Control   Vehicle                1.48</code></pre>
</div>
</div>
<p>Then Figure 5e:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"Fig 5"</span>, <span class="at">range =</span> <span class="st">"C31:AD35"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">col_types =</span> <span class="st">"text"</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>) <span class="co"># reads in the data table we need specifically</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">t</span>(f) <span class="co"># swaps columns with rows, so we can work with the table easier</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">row_to_names</span>(f, <span class="at">row_number =</span> <span class="dv">1</span>) <span class="co"># assigns proper names to columns</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> control <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Control"</span>, <span class="at">times =</span> <span class="dv">9</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> stress <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Stress"</span>, <span class="at">times =</span> <span class="dv">18</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> condition <span class="ot">&lt;-</span> <span class="fu">append</span>(control, <span class="at">values =</span> stress)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f[<span class="dv">1</span><span class="sc">:</span><span class="dv">27</span>] <span class="ot">=</span> condition <span class="co"># fills out missing values for stress condition</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(f, <span class="at">.name_repair =</span> <span class="st">"universal_quiet"</span>) <span class="co"># converts table to a format we can work with easier</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, Vehicle) <span class="sc">%&gt;%</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Sucrose.Preference =</span> <span class="fu">as.numeric</span>(Vehicle)) <span class="sc">%&gt;%</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Sucrose.Preference))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f1 <span class="sc">%&gt;%</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f1))) <span class="sc">%&gt;%</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Sucrose.Preference) <span class="co"># separates all data points since each one is from a different subject, and makes an extra column that keeps track of treatment condition</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT) <span class="sc">%&gt;%</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Sucrose.Preference =</span> <span class="fu">as.numeric</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT)) <span class="sc">%&gt;%</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Sucrose.Preference))</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f2 <span class="sc">%&gt;%</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"..4.F..5.MeO.pyrT"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f2))) <span class="sc">%&gt;%</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Sucrose.Preference)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f3 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, WAY.<span class="fl">100.635</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Sucrose.Preference =</span> <span class="fu">as.numeric</span>(WAY.<span class="fl">100.635</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Sucrose.Preference))</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f3 <span class="ot">&lt;-</span> f3 <span class="sc">%&gt;%</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY.100.635"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f3))) <span class="sc">%&gt;%</span></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Sucrose.Preference)</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f4 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Drug, ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT..WAY.<span class="fl">100.635</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> Drug, <span class="at">Sucrose.Preference =</span> <span class="fu">as.numeric</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.pyrT..WAY.<span class="fl">100.635</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Sucrose.Preference))</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f4 <span class="ot">&lt;-</span> f4 <span class="sc">%&gt;%</span></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"..4.F..5.MeO.pyrT..WAY.100.635"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f4))) <span class="sc">%&gt;%</span></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Treatment, Sucrose.Preference)</span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f5e <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Condition =</span> <span class="fu">character</span>(), <span class="at">Treatment =</span> <span class="fu">character</span>(), <span class="at">Sucrose.Preference =</span> <span class="fu">numeric</span>())</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f5e <span class="ot">&lt;-</span> f5e <span class="sc">%&gt;%</span> <span class="co"># combines all separate treatments into a single usable table</span></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f1) <span class="sc">%&gt;%</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f2) <span class="sc">%&gt;%</span></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f3) <span class="sc">%&gt;%</span></span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f4)</span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f5e))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 3
##   Condition Treatment Sucrose.Preference
##   &lt;chr&gt;     &lt;chr&gt;                  &lt;dbl&gt;
## 1 Control   Vehicle                 76.4
## 2 Control   Vehicle                 91.7
## 3 Control   Vehicle                 86.6
## 4 Control   Vehicle                 94.7
## 5 Control   Vehicle                 77.9
## 6 Control   Vehicle                 88.6</code></pre>
</div>
</div>
<p>Now let’s see Extended Data Figure 7:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Extended Data Figure 7.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Extended%20Data%20Figure%207.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s read in the data for Extended Data Figure 7d:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehveh <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"D35:K35"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>))) <span class="co"># this code chunk one treatment group for this experiment at a time, because it is formatted very inconveniently</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>## Warning: The `x` argument of `as_tibble.matrix()` must have unique column names if
## `.name_repair` is omitted as of tibble 2.0.0.
## ℹ Using compatibility `.name_repair`.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehveh <span class="ot">&lt;-</span> vehveh <span class="sc">%&gt;%</span> <span class="co"># adds a "treatment" column and properly renames the "distance traveled" column</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"Vehicle + Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(vehveh)), <span class="at">Distance.Traveled.cm =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Distance.Traveled.cm)) <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Distance.Traveled.cm)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehmeo <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"L35:S35"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehmeo <span class="ot">&lt;-</span> vehmeo <span class="sc">%&gt;%</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(vehmeo)), <span class="at">Distance.Traveled.cm =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Distance.Traveled.cm)) <span class="sc">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Distance.Traveled.cm)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> waymeo <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"D38:K38"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> waymeo <span class="ot">&lt;-</span> waymeo <span class="sc">%&gt;%</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(waymeo)), <span class="at">Distance.Traveled.cm =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Distance.Traveled.cm)) <span class="sc">%&gt;%</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Distance.Traveled.cm)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2meo <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"L38:S38"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2meo <span class="ot">&lt;-</span> way2meo <span class="sc">%&gt;%</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(way2meo)), <span class="at">Distance.Traveled.cm =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Distance.Traveled.cm)) <span class="sc">%&gt;%</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Distance.Traveled.cm)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> wayveh <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"D41:K41"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> wayveh <span class="ot">&lt;-</span> wayveh <span class="sc">%&gt;%</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 1 mg/kg + Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(wayveh)), <span class="at">Distance.Traveled.cm =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Distance.Traveled.cm)) <span class="sc">%&gt;%</span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Distance.Traveled.cm)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2veh <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"L41:S41"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2veh <span class="ot">&lt;-</span> way2veh <span class="sc">%&gt;%</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 2 mg/kg + Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(way2veh)), <span class="at">Distance.Traveled.cm =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Distance.Traveled.cm)) <span class="sc">%&gt;%</span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Distance.Traveled.cm)</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7d1 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Treatment =</span> <span class="fu">character</span>(), <span class="at">Distance.Traveled.cm =</span> <span class="fu">numeric</span>())</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7d1 <span class="ot">&lt;-</span> f7d1 <span class="sc">%&gt;%</span> <span class="co"># combines all separate treatments into a single usable table</span></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(vehveh) <span class="sc">%&gt;%</span></span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(vehmeo) <span class="sc">%&gt;%</span></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(waymeo) <span class="sc">%&gt;%</span></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(way2meo) <span class="sc">%&gt;%</span></span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(wayveh) <span class="sc">%&gt;%</span></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(way2veh)</span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f7d1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 2
##   Treatment         Distance.Traveled.cm
##   &lt;chr&gt;                            &lt;dbl&gt;
## 1 Vehicle + Vehicle                2938.
## 2 Vehicle + Vehicle                3375.
## 3 Vehicle + Vehicle                3323.
## 4 Vehicle + Vehicle                3395.
## 5 Vehicle + Vehicle                6471.
## 6 Vehicle + Vehicle                4608.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehveh <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"D45:K45"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>))) <span class="co"># this code chunk one treatment group for this experiment at a time, because it is formatted very inconveniently</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehveh <span class="ot">&lt;-</span> vehveh <span class="sc">%&gt;%</span> <span class="co"># adds a "treatment" column and properly renames the "distance traveled" column</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"Vehicle + Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(vehveh)), <span class="at">Head.Twitch.Response =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Head.Twitch.Response)) <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Head.Twitch.Response)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehmeo <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"L45:S45"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> vehmeo <span class="ot">&lt;-</span> vehmeo <span class="sc">%&gt;%</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(vehmeo)), <span class="at">Head.Twitch.Response =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Head.Twitch.Response)) <span class="sc">%&gt;%</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Head.Twitch.Response)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> waymeo <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"D48:K48"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> waymeo <span class="ot">&lt;-</span> waymeo <span class="sc">%&gt;%</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(waymeo)), <span class="at">Head.Twitch.Response =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Head.Twitch.Response)) <span class="sc">%&gt;%</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Head.Twitch.Response)</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2meo <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"L48:S48"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2meo <span class="ot">&lt;-</span> way2meo <span class="sc">%&gt;%</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(way2meo)), <span class="at">Head.Twitch.Response =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Head.Twitch.Response)) <span class="sc">%&gt;%</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Head.Twitch.Response)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> wayveh <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"D51:K51"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> wayveh <span class="ot">&lt;-</span> wayveh <span class="sc">%&gt;%</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 1 mg/kg + Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(wayveh)), <span class="at">Head.Twitch.Response =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Head.Twitch.Response)) <span class="sc">%&gt;%</span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Head.Twitch.Response)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2veh <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">t</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"L51:S51"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>)))</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> way2veh <span class="ot">&lt;-</span> way2veh <span class="sc">%&gt;%</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">rep</span>(<span class="st">"WAY-100,635 2 mg/kg + Vehicle"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(way2veh)), <span class="at">Head.Twitch.Response =</span> V1) <span class="sc">%&gt;%</span></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Head.Twitch.Response)) <span class="sc">%&gt;%</span></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Treatment, Head.Twitch.Response)</span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7d2 <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Treatment =</span> <span class="fu">character</span>(), <span class="at">Head.Twitch.Response =</span> <span class="fu">numeric</span>())</span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7d2 <span class="ot">&lt;-</span> f7d2 <span class="sc">%&gt;%</span> <span class="co"># combines all separate treatments into a single usable table</span></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(vehveh) <span class="sc">%&gt;%</span></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(vehmeo) <span class="sc">%&gt;%</span></span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(waymeo) <span class="sc">%&gt;%</span></span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(way2meo) <span class="sc">%&gt;%</span></span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(wayveh) <span class="sc">%&gt;%</span></span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(way2veh)</span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f7d2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 2
##   Treatment         Head.Twitch.Response
##   &lt;chr&gt;                            &lt;dbl&gt;
## 1 Vehicle + Vehicle                    1
## 2 Vehicle + Vehicle                    0
## 3 Vehicle + Vehicle                    0
## 4 Vehicle + Vehicle                    1
## 5 Vehicle + Vehicle                    1
## 6 Vehicle + Vehicle                    2</code></pre>
</div>
</div>
<p>And now Extended Data Figure 7e:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"C63:W65"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">col_types =</span> <span class="st">"text"</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>) <span class="co"># reads in the data table we need specifically</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">t</span>(f) <span class="co"># swaps columns with rows, so we can work with the table easier</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">row_to_names</span>(f, <span class="at">row_number =</span> <span class="dv">1</span>) <span class="co"># assigns proper names to columns</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> control <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Control"</span>, <span class="at">times =</span> <span class="dv">8</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> stress <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Stress"</span>, <span class="at">times =</span> <span class="dv">12</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> condition <span class="ot">&lt;-</span> <span class="fu">append</span>(control, <span class="at">values =</span> stress)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>] <span class="ot">=</span> condition <span class="co"># fills out missing values for stress condition</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(f, <span class="at">.name_repair =</span> <span class="st">"universal_quiet"</span>) <span class="co"># converts table to a format we can work with easier</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., ...<span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., <span class="at">Distance.Moved.cm =</span> <span class="fu">as.numeric</span>(...<span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(...<span class="dv">0</span>))</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f1 <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Dosage =</span> <span class="fu">rep</span>(<span class="st">"0"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f1))) <span class="sc">%&gt;%</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Dosage, Distance.Moved.cm) <span class="co"># separates all data points since each one is from a different subject, and makes an extra column that keeps track of treatment condition</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., ..<span class="fl">1.0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., <span class="at">Distance.Moved.cm =</span> <span class="fu">as.numeric</span>(..<span class="fl">1.0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(..<span class="fl">1.0</span>))</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f2 <span class="sc">%&gt;%</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Dosage =</span> <span class="fu">rep</span>(<span class="st">"1.0"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f2))) <span class="sc">%&gt;%</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Dosage, Distance.Moved.cm)</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7e <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Condition =</span> <span class="fu">character</span>(), <span class="at">Dosage =</span> <span class="fu">character</span>(), <span class="at">Distance.Moved.cm =</span> <span class="fu">numeric</span>())</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7e <span class="ot">&lt;-</span> f7e <span class="sc">%&gt;%</span> <span class="co"># combines all separate treatments into a single usable table</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f1) <span class="sc">%&gt;%</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f2)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f7e))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 3
##   Condition Dosage Distance.Moved.cm
##   &lt;chr&gt;     &lt;chr&gt;              &lt;dbl&gt;
## 1 Control   0                  1147.
## 2 Control   0                  1154.
## 3 Control   0                   578.
## 4 Control   0                   945.
## 5 Control   0                   727.
## 6 Control   0                  1251.</code></pre>
</div>
</div>
<p>Extended Data Figure 7f:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"C53:W55"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">col_types =</span> <span class="st">"text"</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>) <span class="co"># reads in the data table we need specifically</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">t</span>(f) <span class="co"># swaps columns with rows, so we can work with the table easier</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">row_to_names</span>(f, <span class="at">row_number =</span> <span class="dv">1</span>) <span class="co"># assigns proper names to columns</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> control <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Control"</span>, <span class="at">times =</span> <span class="dv">8</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> stress <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Stress"</span>, <span class="at">times =</span> <span class="dv">12</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> condition <span class="ot">&lt;-</span> <span class="fu">append</span>(control, <span class="at">values =</span> stress)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>] <span class="ot">=</span> condition <span class="co"># fills out missing values for stress condition</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(f, <span class="at">.name_repair =</span> <span class="st">"universal_quiet"</span>) <span class="co"># converts table to a format we can work with easier</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., ...<span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(...<span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(...<span class="dv">0</span>))</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f1 <span class="sc">%&gt;%</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Dosage =</span> <span class="fu">rep</span>(<span class="st">"0"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f1))) <span class="sc">%&gt;%</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Dosage, Interaction.Ratio) <span class="co"># separates all data points since each one is from a different subject, and makes an extra column that keeps track of treatment condition</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., ..<span class="fl">1.0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(..<span class="fl">1.0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(..<span class="fl">1.0</span>))</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f2 <span class="sc">%&gt;%</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Dosage =</span> <span class="fu">rep</span>(<span class="st">"1.0"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f2))) <span class="sc">%&gt;%</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Dosage, Interaction.Ratio)</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7f <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Condition =</span> <span class="fu">character</span>(), <span class="at">Dosage =</span> <span class="fu">character</span>(), <span class="at">Interaction.Ratio =</span> <span class="fu">numeric</span>())</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7f <span class="ot">&lt;-</span> f7f <span class="sc">%&gt;%</span> <span class="co"># combines all separate treatments into a single usable table</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f1) <span class="sc">%&gt;%</span></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f2)</span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f7f))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 3
##   Condition Dosage Interaction.Ratio
##   &lt;chr&gt;     &lt;chr&gt;              &lt;dbl&gt;
## 1 Control   0                  1.62 
## 2 Control   0                  1.28 
## 3 Control   0                  0.818
## 4 Control   0                  1.14 
## 5 Control   0                  0.797
## 6 Control   0                  1.26</code></pre>
</div>
</div>
<p>Extended Data Figure G:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>, <span class="at">range =</span> <span class="st">"C58:W60"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>, <span class="at">col_types =</span> <span class="st">"text"</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>) <span class="co"># reads in the data table we need specifically</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">t</span>(f) <span class="co"># swaps columns with rows, so we can work with the table easier</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">row_to_names</span>(f, <span class="at">row_number =</span> <span class="dv">1</span>) <span class="co"># assigns proper names to columns</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> control <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Control"</span>, <span class="at">times =</span> <span class="dv">8</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> stress <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"Stress"</span>, <span class="at">times =</span> <span class="dv">12</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> condition <span class="ot">&lt;-</span> <span class="fu">append</span>(control, <span class="at">values =</span> stress)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>] <span class="ot">=</span> condition <span class="co"># fills out missing values for stress condition</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(f, <span class="at">.name_repair =</span> <span class="st">"universal_quiet"</span>) <span class="co"># converts table to a format we can work with easier</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., ...<span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(...<span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(...<span class="dv">0</span>))</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f1 <span class="ot">&lt;-</span> f1 <span class="sc">%&gt;%</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Dosage =</span> <span class="fu">rep</span>(<span class="st">"0"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f1))) <span class="sc">%&gt;%</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Dosage, Interaction.Ratio) <span class="co"># separates all data points since each one is from a different subject, and makes an extra column that keeps track of treatment condition</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f <span class="sc">%&gt;%</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., ..<span class="fl">1.0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Condition =</span> ..<span class="fl">4.</span>F..<span class="fl">5.</span>MeO.PyrT...mg.kg., <span class="at">Interaction.Ratio =</span> <span class="fu">as.numeric</span>(..<span class="fl">1.0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(..<span class="fl">1.0</span>))</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f2 <span class="ot">&lt;-</span> f2 <span class="sc">%&gt;%</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">mutate</span>(<span class="at">Dosage =</span> <span class="fu">rep</span>(<span class="st">"1.0"</span>, <span class="at">times =</span> <span class="fu">nrow</span>(f2))) <span class="sc">%&gt;%</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">select</span>(Condition, Dosage, Interaction.Ratio)</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7g <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Condition =</span> <span class="fu">character</span>(), <span class="at">Dosage =</span> <span class="fu">character</span>(), <span class="at">Interaction.Ratio =</span> <span class="fu">numeric</span>())</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7g <span class="ot">&lt;-</span> f7g <span class="sc">%&gt;%</span> <span class="co"># combines all separate treatments into a single usable table</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f1) <span class="sc">%&gt;%</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>   <span class="fu">add_row</span>(f2)</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f7g))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 6 × 3
##   Condition Dosage Interaction.Ratio
##   &lt;chr&gt;     &lt;chr&gt;              &lt;dbl&gt;
## 1 Control   0                  1.06 
## 2 Control   0                  0.706
## 3 Control   0                  0.706
## 4 Control   0                  0.276
## 5 Control   0                  1.32 
## 6 Control   0                  0.778</code></pre>
</div>
</div>
<p>And finally, Extended Data Figure 7h:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> f7h <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="fu">read_excel</span>(<span class="at">path =</span> <span class="st">"data/41586_2024_7403_MOESM5_ESM.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"ED Fig 7"</span>,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="at">range =</span> <span class="st">"C68:E70"</span>, <span class="at">.name_repair =</span> <span class="st">"unique_quiet"</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">head</span>(f7h))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 2 × 3
##   `4-F, 5-MeO-PyrT\r\n(mg/kg)` Susceptible Resilient
##   &lt;chr&gt;                              &lt;dbl&gt;     &lt;dbl&gt;
## 1 0                                     19        10
## 2 1.0                                   13        23</code></pre>
</div>
</div>
</section>
<section id="statistical-replicationsreanalysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-replicationsreanalysis">Statistical Replications/Reanalysis</h2>
<section id="figure-5d" class="level3">
<h3 class="anchored" data-anchor-id="figure-5d">Figure 5d</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Figure 5d.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Figure%205d.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>This first set of data was analyzed using a two-way ANOVA with multiple comparisons and, for post-hoc tests, Fisher’s least significant difference tests.</p>
<p>First, let’s make sure we have the correct group sizes:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">unique</span>(f5d<span class="sc">$</span>Treatment)) {</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="co"># checks each treatment group checks each stress condition within each</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="co"># treatment group</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">unique</span>(f5d<span class="sc">$</span>Condition)) {</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>         <span class="fu">cat</span>(<span class="st">"Group Size for "</span>, i, <span class="st">" "</span>, j, <span class="st">":"</span>, <span class="fu">nrow</span>(<span class="fu">filter</span>(f5d, Treatment <span class="sc">==</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>             i <span class="sc">&amp;</span> Condition <span class="sc">==</span> j)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     }</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span> }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Group Size for  Vehicle   Control : 17 
## Group Size for  Vehicle   Stress : 29 
## Group Size for  ..4.F..5.MeO.pyrT   Control : 17 
## Group Size for  ..4.F..5.MeO.pyrT   Stress : 36 
## Group Size for  WAY.100.635   Control : 5 
## Group Size for  WAY.100.635   Stress : 10 
## Group Size for  ..4.F..5.MeO.pyrT..WAY.100.635   Control : 10 
## Group Size for  ..4.F..5.MeO.pyrT..WAY.100.635   Stress : 19</code></pre>
</div>
</div>
<p>Looks great! now let’s graph it:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> f5d, <span class="fu">aes</span>(<span class="at">x =</span> Treatment, <span class="at">y =</span> Interaction.Ratio, <span class="at">fill =</span> Condition)) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/unnamed-chunk-15-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s do that two-way ANOVA. It looks like they were trying to look at main effect of stress condition, main effect of treatment group, and any interaction effects between the two:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> f5d, Interaction.Ratio <span class="sc">~</span> Condition <span class="sc">*</span> Treatment)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Condition             1  2.570  2.5701  15.276 0.000146 ***
## Treatment             3  2.159  0.7196   4.277 0.006419 ** 
## Condition:Treatment   3  0.840  0.2799   1.664 0.177798    
## Residuals           135 22.714  0.1683                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>It looks like there are main effects of condition and treatment, and no two-way interaction! This makes sense, since 4-F,5-MeO-PyrT was found to reverse the effect of stress on interaction ratio, and WAY-100635 is meant to prevent that reversal, so things start cancelling each other out when they combine. My p values are mostly in line with the authors’; the treatment factor is the only one that differs, and I can only explain it as being a typo at this point.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Highlight 1.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Highlight%201.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Anyway, let’s move on to the Fisher’s least significant difference tests:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m1, <span class="at">trt =</span> <span class="st">"Condition"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##     MSerror  Df     Mean       CV
##   0.1682505 135 1.094766 37.46768
## 
## $parameters
##         test p.ajusted    name.t ntr alpha
##   Fisher-LSD      none Condition   2  0.05
## 
## $means
##         Interaction.Ratio       std  r         se       LCL      UCL      Min
## Control         1.2804513 0.2848818 49 0.05859764 1.1645632 1.396339 0.789090
## Stress          0.9979729 0.4843435 94 0.04230720 0.9143023 1.081644 0.008466
##              Max       Q25       Q50      Q75
## Control 1.932631 1.0525160 1.2668340 1.479240
## Stress  2.327479 0.6728863 0.9262825 1.270895
## 
## $comparison
## NULL
## 
## $groups
##         Interaction.Ratio groups
## Control         1.2804513      a
## Stress          0.9979729      b
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m1, <span class="at">trt =</span> <span class="st">"Treatment"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##     MSerror  Df     Mean       CV
##   0.1682505 135 1.094766 37.46768
## 
## $parameters
##         test p.ajusted    name.t ntr alpha
##   Fisher-LSD      none Treatment   4  0.05
## 
## $means
##                                Interaction.Ratio       std  r         se
## ..4.F..5.MeO.pyrT                      1.2480945 0.4139456 53 0.05634303
## ..4.F..5.MeO.pyrT..WAY.100.635         0.9983638 0.5603473 29 0.07616916
## Vehicle                                1.0182629 0.4035466 46 0.06047826
## WAY.100.635                            0.9739947 0.2986561 15 0.10590892
##                                      LCL      UCL      Min      Max       Q25
## ..4.F..5.MeO.pyrT              1.1366653 1.359524 0.402874 2.304008 0.9676820
## ..4.F..5.MeO.pyrT..WAY.100.635 0.8477246 1.149003 0.008466 2.327479 0.5475500
## Vehicle                        0.8986555 1.137870 0.261253 1.878849 0.7081427
## WAY.100.635                    0.7645394 1.183450 0.366197 1.598349 0.8291150
##                                     Q50      Q75
## ..4.F..5.MeO.pyrT              1.238643 1.549786
## ..4.F..5.MeO.pyrT..WAY.100.635 0.938742 1.442857
## Vehicle                        1.078493 1.282312
## WAY.100.635                    0.943684 1.086404
## 
## $comparison
## NULL
## 
## $groups
##                                Interaction.Ratio groups
## ..4.F..5.MeO.pyrT                      1.2480945      a
## Vehicle                                1.0182629      b
## ..4.F..5.MeO.pyrT..WAY.100.635         0.9983638      b
## WAY.100.635                            0.9739947      b
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
</div>
<p>I am unable to retrieve p values for the Fischer’s tests for some reason, but the groups analysis do seem to confirm that there is a main stress effect, and that 4-F,5-MeO-PyrT can rescue interaction ratio in stressed mice, but only in absence of WAY-100635.</p>
</section>
<section id="figure-5e" class="level3">
<h3 class="anchored" data-anchor-id="figure-5e">Figure 5e</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Figure 5e.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Figure%205e.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>This next section did something similar, with two-way ANOVA and Fisher’s LSDs. Let’s start by checking our sample sizes again:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">unique</span>(f5e<span class="sc">$</span>Treatment)) {</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="co"># checks each treatment group checks each stress condition within each</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="co"># treatment group</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">unique</span>(f5e<span class="sc">$</span>Condition)) {</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>         <span class="fu">cat</span>(<span class="st">"Group Size for "</span>, i, <span class="st">" "</span>, j, <span class="st">":"</span>, <span class="fu">nrow</span>(<span class="fu">filter</span>(f5e, Treatment <span class="sc">==</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>             i <span class="sc">&amp;</span> Condition <span class="sc">==</span> j)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     }</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span> }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## Group Size for  Vehicle   Control : 9 
## Group Size for  Vehicle   Stress : 18 
## Group Size for  ..4.F..5.MeO.pyrT   Control : 9 
## Group Size for  ..4.F..5.MeO.pyrT   Stress : 18 
## Group Size for  WAY.100.635   Control : 5 
## Group Size for  WAY.100.635   Stress : 10 
## Group Size for  ..4.F..5.MeO.pyrT..WAY.100.635   Control : 5 
## Group Size for  ..4.F..5.MeO.pyrT..WAY.100.635   Stress : 10</code></pre>
</div>
</div>
<p>Great! Let’s graph this one too:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> f5e, <span class="fu">aes</span>(<span class="at">x =</span> Treatment, <span class="at">y =</span> Sucrose.Preference, <span class="at">fill =</span> Condition)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can do this one’s two-way ANOVA now:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> f5e, Sucrose.Preference <span class="sc">~</span> Condition <span class="sc">*</span> Treatment)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##                     Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Condition            1   3130  3130.0  11.505 0.001104 ** 
## Treatment            3   4910  1636.8   6.016 0.000985 ***
## Condition:Treatment  3   1933   644.3   2.368 0.077305 .  
## Residuals           76  20676   272.0                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Again, it looks like main effects of stress condition and treatment group, with no two-way interaction. The p value for the interaction effect is in line perfectly again, but condition and treatment are slightly off again.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Highlight 1.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Highlight%201.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>We can do the Fisher’s least significant difference test again:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m2, <span class="at">trt =</span> <span class="st">"Condition"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##    MSerror Df     Mean       CV
##   272.0485 76 73.37604 22.47858
## 
## $parameters
##         test p.ajusted    name.t ntr alpha
##   Fisher-LSD      none Condition   2  0.05
## 
## $means
##         Sucrose.Preference       std  r       se      LCL      UCL      Min
## Control           82.00871  9.119043 28 3.117053 75.80056 88.21686 60.24096
## Stress            69.05970 21.436442 56 2.204089 64.66988 73.44953 10.52632
##              Max      Q25      Q50      Q75
## Control 95.91837 77.93640 82.03812 87.51337
## Stress  95.96123 62.31306 76.28968 83.48765
## 
## $comparison
## NULL
## 
## $groups
##         Sucrose.Preference groups
## Control           82.00871      a
## Stress            69.05970      b
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m2, <span class="at">trt =</span> <span class="st">"Treatment"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##    MSerror Df     Mean       CV
##   272.0485 76 73.37604 22.47858
## 
## $parameters
##         test p.ajusted    name.t ntr alpha
##   Fisher-LSD      none Treatment   4  0.05
## 
## $means
##                                Sucrose.Preference       std  r       se
## ..4.F..5.MeO.pyrT                        80.52160  7.980796 27 3.174251
## ..4.F..5.MeO.pyrT..WAY.100.635           58.23270 28.462048 15 4.258705
## Vehicle                                  73.27037 18.934114 27 3.174251
## WAY.100.635                              75.84758 15.630225 15 4.258705
##                                     LCL      UCL      Min      Max      Q25
## ..4.F..5.MeO.pyrT              74.19953 86.84367 62.74510 95.96123 77.47264
## ..4.F..5.MeO.pyrT..WAY.100.635 49.75075 66.71464 10.52632 89.65517 39.31419
## Vehicle                        66.94830 79.59244 17.91045 94.73684 65.16946
## WAY.100.635                    67.36564 84.32953 31.74603 95.91837 72.98335
##                                     Q50      Q75
## ..4.F..5.MeO.pyrT              80.95238 85.61077
## ..4.F..5.MeO.pyrT..WAY.100.635 61.84211 80.98252
## Vehicle                        78.48101 86.91995
## WAY.100.635                    77.92208 84.62441
## 
## $comparison
## NULL
## 
## $groups
##                                Sucrose.Preference groups
## ..4.F..5.MeO.pyrT                        80.52160      a
## WAY.100.635                              75.84758      a
## Vehicle                                  73.27037      a
## ..4.F..5.MeO.pyrT..WAY.100.635           58.23270      b
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
</div>
<p>And again, this confirms the main effects of condition and treatment, with 4-F,5-MeO-PyrT combined with WAY-100635 being the odd one out this time.</p>
</section>
<section id="extended-data-figure-7d1" class="level3">
<h3 class="anchored" data-anchor-id="extended-data-figure-7d1">Extended Data Figure 7d1</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Extended Data Figure 7d.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Extended%20Data%20Figure%207d.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>ED Fig 7d was done using one-way ANOVAs with multiple comparisons and Tukey’s post-hoc test. Let’s start by graphing it:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> f7d1, <span class="fu">aes</span>(<span class="at">x =</span> Treatment, <span class="at">y =</span> Distance.Traveled.cm)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="at">stat =</span> <span class="st">"identity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/unnamed-chunk-26-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>And now let’s get into the ANOVA:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> f7d1, Distance.Traveled.cm <span class="sc">~</span> Treatment)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##             Df   Sum Sq  Mean Sq F value   Pr(&gt;F)    
## Treatment    5 66706636 13341327   13.26 1.05e-07 ***
## Residuals   41 41251222  1006127                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The authors did not report any statistics on the ANOVA, but there is a main effect of treatment!</p>
<p>Onto the Tukey’s post-hoc tests:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> posthoc <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(m3, <span class="at">which =</span> <span class="st">"Treatment"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> posthoc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Distance.Traveled.cm ~ Treatment, data = f7d1)
## 
## $Treatment
##                                                                                               diff
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                      3399.0728
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg            3191.0962
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                          3084.7375
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg            1570.0373
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                          2211.4118
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                            -207.9766
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                          -314.3353
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           -1829.0355
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                         -1187.6610
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg                -106.3587
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg -1621.0589
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg                -979.6844
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle               -1514.7002
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                              -873.3257
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg                 641.3745
##                                                                                                lwr
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                      1900.1772
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg            1692.2006
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                          1533.2332
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg              71.1417
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                           712.5162
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           -1706.8723
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                         -1865.8397
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           -3327.9311
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                         -2686.5566
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               -1657.8631
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg -3119.9545
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               -2478.5800
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle               -3066.2046
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                             -2424.8301
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg                -857.5211
##                                                                                                upr
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                     4897.96847
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           4689.99185
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         4636.24192
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           3068.93297
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         3710.30747
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           1290.91901
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                         1237.16908
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           -330.13986
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                          311.23464
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               1445.14571
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg -122.16324
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg                519.21126
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle                 36.80419
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                              678.17869
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg               2140.27014
##                                                                                             p adj
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                     0.0000005
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           0.0000019
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         0.0000075
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           0.0353275
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         0.0009739
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           0.9983128
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                         0.9900470
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           0.0090301
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                         0.1914722
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               0.9999462
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg 0.0273218
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               0.3858792
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle               0.0591781
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                             0.5508703
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg               0.7946016</code></pre>
</div>
</div>
<p>The comparable p values from this are (formatted as my calculated values vs the authors’ reported values):</p>
<p>Vehicle-Vehicle, Vehicle-1 mg/kg 4-F,5-MeO-PyrT: 0.0000005 vs 0.0000006 1 mg/kg WAY100635 + 1 mg/kg 4-F,5-MeO-PyrT-1 mg/kg 4-F,5-MeO-PyrT: 0.0000019 vs 0.0000019 1 mg/kg WAY100635 + 1 mg/kg 4-F,5-MeO-PyrT-1 mg/kg 4-F,5-MeO-PyrT: 0.0353275 vs 0.0353275 2 mg/kg WAY100635-1 mg/kg WAY100635: 0.5508703 vs 0.5508703</p>
<p>In summary: The post-hoc tests look pretty good!</p>
</section>
<section id="extended-data-figure-7d2" class="level3">
<h3 class="anchored" data-anchor-id="extended-data-figure-7d2">Extended Data Figure 7d2</h3>
<p>This one is also an ANOVA:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m4 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> f7d2, Head.Twitch.Response <span class="sc">~</span> Treatment)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## Treatment    5  22.97   4.594    2.98 0.0267 *
## Residuals   30  46.25   1.542                 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>No ANOVA statistics reported by the authors again, but there’s significance again!</p>
<p>Onto the Tukey’s post-hoc tests:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> posthoc <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(m4, <span class="at">which =</span> <span class="st">"Treatment"</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> posthoc</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Head.Twitch.Response ~ Treatment, data = f7d2)
## 
## $Treatment
##                                                                                           diff
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                      0.625
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg            2.500
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                          1.125
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg            1.250
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                          1.750
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                            1.875
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                          0.500
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                            0.625
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                          1.125
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               -1.375
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg -1.250
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               -0.750
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle                0.125
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                              0.625
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg                0.500
##                                                                                                 lwr
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                     -1.68766194
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg            0.18733806
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         -1.18766194
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           -1.42043199
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         -0.92043199
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           -0.01328057
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                         -1.38828057
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           -1.68766194
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                         -1.18766194
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               -3.26328057
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg -3.56266194
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               -3.06266194
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle               -2.18766194
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                             -1.68766194
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg               -2.17043199
##                                                                                               upr
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                     2.9376619
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           4.8126619
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         3.4376619
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           3.9204320
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         4.4204320
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           3.7632806
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                         2.3882806
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           2.9376619
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                         3.4376619
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               0.5132806
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg 1.0626619
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               1.5626619
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle               2.4376619
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                             2.9376619
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg               3.1704320
##                                                                                             p adj
## Vehicle + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                                     0.9611003
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           0.0281554
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         0.6793023
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg           0.7127694
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + 4-F, 5-MeO-PyrT 1 mg/kg                         0.3695501
## WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           0.0524797
## WAY-100,635 1 mg/kg + Vehicle-Vehicle + Vehicle                                         0.9643016
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-Vehicle + Vehicle                           0.9611003
## WAY-100,635 2 mg/kg + Vehicle-Vehicle + Vehicle                                         0.6793023
## WAY-100,635 1 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               0.2608798
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg 0.5773332
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + 4-F, MeO-PyrT 1 mg/kg               0.9187085
## WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg-WAY-100,635 1 mg/kg + Vehicle               0.9999814
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 1 mg/kg + Vehicle                             0.9611003
## WAY-100,635 2 mg/kg + Vehicle-WAY-100,635 2 mg/kg + 4-F, MeO-PyrT 1 mg/kg               0.9923060</code></pre>
</div>
</div>
<p>The only comparison we can check is 1 mg/kg WAY-100635-1 mg/kg 4-F,5-MeO-PyrT, whose calculated p value is… 0.6793023. Way off from 0.0039 for some reason.</p>
</section>
<section id="extended-data-7e" class="level3">
<h3 class="anchored" data-anchor-id="extended-data-7e">Extended Data 7e</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Extended Data Figure 7e.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Extended%20Data%20Figure%207e.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>ED Fig 7e was analyzed by two-way ANOVA and Fisher’s LSD post-hoc test. Let’s graph it:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> f7e, <span class="fu">aes</span>(<span class="at">x =</span> Dosage, <span class="at">y =</span> Distance.Moved.cm, <span class="at">fill =</span> Condition)) <span class="sc">+</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/unnamed-chunk-32-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s do the ANOVA:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m5 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> f7e, Distance.Moved.cm <span class="sc">~</span> Condition <span class="sc">*</span> Dosage)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##                  Df  Sum Sq Mean Sq F value Pr(&gt;F)
## Condition         1     482     482   0.013  0.910
## Dosage            1    1238    1238   0.033  0.857
## Condition:Dosage  1   72831   72831   1.938  0.173
## Residuals        35 1315013   37572</code></pre>
</div>
</div>
<p>No statistics were reported for this by the authors, but this is no surprise given the lack of significance markers on their graph. Onto the Fisher’s post-hoc tests:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m5, <span class="at">trt =</span> <span class="st">"Condition"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##   MSerror Df     Mean       CV
##   37571.8 35 902.1176 21.48661
## 
## $parameters
##         test p.ajusted    name.t ntr alpha
##   Fisher-LSD      none Condition   2  0.05
## 
## $means
##         Distance.Moved.cm      std  r       se      LCL       UCL     Min
## Control          906.3338 189.4011 16 48.45862 807.9575 1004.7100 578.445
## Stress           899.1847 196.6758 23 40.41728 817.1332  981.2361 413.750
##             Max      Q25     Q50      Q75
## Control 1250.94 767.6368 887.658 1017.345
## Stress  1182.50 806.0605 937.411 1034.460
## 
## $comparison
## NULL
## 
## $groups
##         Distance.Moved.cm groups
## Control          906.3338      a
## Stress           899.1847      a
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m5, <span class="at">trt =</span> <span class="st">"Dosage"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##   MSerror Df     Mean       CV
##   37571.8 35 902.1176 21.48661
## 
## $parameters
##         test p.ajusted name.t ntr alpha
##   Fisher-LSD      none Dosage   2  0.05
## 
## $means
##     Distance.Moved.cm      std  r       se      LCL      UCL     Min     Max
## 0            896.4167 201.4847 19 44.46868 806.1405 986.6930 413.750 1250.94
## 1.0          907.5335 186.0433 20 43.34271 819.5431 995.5238 508.215 1182.50
##          Q25     Q50       Q75
## 0   806.0605 937.411  967.7725
## 1.0 767.6368 901.186 1059.3600
## 
## $comparison
## NULL
## 
## $groups
##     Distance.Moved.cm groups
## 1.0          907.5335      a
## 0            896.4167      a
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
</div>
<p>And like the ANOVA alluded to, the post-hoc groups confirmed there are not significant differences between the treatments and dosages.</p>
</section>
<section id="extended-data-7f" class="level3">
<h3 class="anchored" data-anchor-id="extended-data-7f">Extended Data 7f</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Extended Data Figure 7f.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Extended%20Data%20Figure%207f.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>ED Fig 7f was also analyzed using two-way ANOVA and Fisher’s least-significant difference tests. Onto graphing it:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> f7f, <span class="fu">aes</span>(<span class="at">x =</span> Dosage, <span class="at">y =</span> Interaction.Ratio, <span class="at">fill =</span> Condition)) <span class="sc">+</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/unnamed-chunk-36-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>And onto the ANOVA:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m6 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> f7f, Interaction.Ratio <span class="sc">~</span> Condition <span class="sc">*</span> Dosage)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##                  Df Sum Sq Mean Sq F value Pr(&gt;F)  
## Condition         1  0.007  0.0065   0.033 0.8567  
## Dosage            1  0.746  0.7463   3.797 0.0596 .
## Condition:Dosage  1  0.392  0.3923   1.996 0.1668  
## Residuals        34  6.682  0.1965                 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This didn’t provide any statistical significance, but there is still a chance to see something in the Fisher post-hoc:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m6, <span class="at">trt =</span> <span class="st">"Condition"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##     MSerror Df     Mean       CV
##   0.1965346 34 1.163406 38.10556
## 
## $parameters
##         test p.ajusted    name.t ntr alpha
##   Fisher-LSD      none Condition   2  0.05
## 
## $means
##         Interaction.Ratio       std  r         se       LCL      UCL      Min
## Control          1.179605 0.2991963 15 0.11446531 0.9469834 1.412226 0.789090
## Stress           1.152841 0.5463712 23 0.09243908 0.9649822 1.340700 0.362814
##              Max      Q25      Q50      Q75
## Control 1.760285 0.909707 1.222603 1.322313
## Stress  2.930953 0.841490 1.098030 1.445124
## 
## $comparison
## NULL
## 
## $groups
##         Interaction.Ratio groups
## Control          1.179605      a
## Stress           1.152841      a
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m6, <span class="at">trt =</span> <span class="st">"Dosage"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##     MSerror Df     Mean       CV  t.value       LSD
##   0.1965346 34 1.163406 38.10556 2.032245 0.2923033
## 
## $parameters
##         test p.ajusted name.t ntr alpha
##   Fisher-LSD      none Dosage   2  0.05
## 
## $means
##     Interaction.Ratio      std  r        se       LCL      UCL      Min
## 0            1.024172 0.385109 19 0.1017051 0.8174824 1.230862 0.362814
## 1.0          1.302639 0.495592 19 0.1017051 1.0959496 1.509329 0.789090
##          Max       Q25      Q50      Q75
## 0   1.878849 0.7431255 1.098030 1.267518
## 1.0 2.930953 0.9322665 1.238643 1.511939
## 
## $comparison
## NULL
## 
## $groups
##     Interaction.Ratio groups
## 1.0          1.302639      a
## 0            1.024172      a
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
</div>
<p>And while no p values are printed by this test, the groups reveal there is no significant difference between the groups either.</p>
</section>
<section id="extended-data-figure-7g" class="level3">
<h3 class="anchored" data-anchor-id="extended-data-figure-7g">Extended Data Figure 7g</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Extended Data Figure 7g.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Extended%20Data%20Figure%207g.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Again, this one was analyzed using two-way ANOVA and a Fisher’s LSD post-hoc test.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">ggplot</span>(<span class="at">data =</span> f7g, <span class="fu">aes</span>(<span class="at">x =</span> Dosage, <span class="at">y =</span> Interaction.Ratio, <span class="at">fill =</span> Condition)) <span class="sc">+</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="sc">+</span>     <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">stat =</span> <span class="st">"identity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/unnamed-chunk-40-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The two-way ANOVA:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> m7 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data =</span> f7g, Interaction.Ratio <span class="sc">~</span> Condition <span class="sc">*</span> Dosage)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">summary</span>(m7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##                  Df Sum Sq Mean Sq F value Pr(&gt;F)  
## Condition         1  0.432  0.4317   1.327  0.257  
## Dosage            1  0.965  0.9655   2.968  0.094 .
## Condition:Dosage  1  0.508  0.5084   1.563  0.220  
## Residuals        34 11.062  0.3253                 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>No significance here again. Let’s look at the Fisher’s post-hoc:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m7, <span class="at">trt =</span> <span class="st">"Condition"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##     MSerror Df     Mean      CV
##   0.3253413 34 1.063425 53.6368
## 
## $parameters
##         test p.ajusted    name.t ntr alpha
##   Fisher-LSD      none Condition   2  0.05
## 
## $means
##         Interaction.Ratio       std  r        se       LCL      UCL      Min
## Control         0.9314359 0.4474635 15 0.1472733 0.6321406 1.230731 0.275650
## Stress          1.1495042 0.6651180 23 0.1189339 0.9078014 1.391207 0.361953
##              Max       Q25      Q50      Q75
## Control 1.655535 0.6914110 0.778482 1.335554
## Stress  2.907260 0.6965665 0.983742 1.372158
## 
## $comparison
## NULL
## 
## $groups
##         Interaction.Ratio groups
## Stress          1.1495042      a
## Control         0.9314359      a
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">print</span>(<span class="fu">LSD.test</span>(m7, <span class="at">trt =</span> <span class="st">"Dosage"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $statistics
##     MSerror Df     Mean      CV  t.value      LSD
##   0.3253413 34 1.063425 53.6368 2.032245 0.376083
## 
## $parameters
##         test p.ajusted name.t ntr alpha
##   Fisher-LSD      none Dosage   2  0.05
## 
## $means
##     Interaction.Ratio       std  r        se       LCL      UCL      Min
## 0           1.2168528 0.6790362 19 0.1308557 0.9509220 1.482784 0.275650
## 1.0         0.9099964 0.4578403 19 0.1308557 0.6440655 1.175927 0.339506
##          Max       Q25      Q50      Q75
## 0   2.907260 0.7421825 1.070589 1.415623
## 1.0 1.899299 0.5381260 0.866210 1.343668
## 
## $comparison
## NULL
## 
## $groups
##     Interaction.Ratio groups
## 0           1.2168528      a
## 1.0         0.9099964      a
## 
## attr(,"class")
## [1] "group"</code></pre>
</div>
</div>
<p>And still no significance, with no explanation for the significance marker on the authors’ figure.</p>
</section>
<section id="extended-data-figure-7h" class="level3">
<h3 class="anchored" data-anchor-id="extended-data-figure-7h">Extended Data Figure 7h</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Extended Data Figure 7h.png"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/Extended%20Data%20Figure%207h.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>This data was analyzed using a two-sided Fisher’s exact test:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">13</span>, <span class="dv">10</span>, <span class="dv">23</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span> <span class="fu">fisher.test</span>(mat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
##  Fisher's Exact Test for Count Data
## 
## data:  mat
## p-value = 0.02533
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##   1.080377 10.651901
## sample estimates:
## odds ratio 
##   3.295621</code></pre>
</div>
</div>
<p>I was forced to write the numbers in manually instead of being able to call them from the tibble, but the p value is right on the dot!</p>
</section>
</section>
<section id="summarydiscussion" class="level2">
<h2 class="anchored" data-anchor-id="summarydiscussion">Summary/Discussion</h2>
<p>In sum, I was not entirely able to replicate the analyses in the study. A major limiting factor was the authors not speaking on the specifics of the statistical tests or corrections they were using, as well as them simply not reporting the results of the statistical tests they ran. This may have been what led to differing p values between my calculations and the authors’ report–if I knew what type of ANOVA they ran, or if they were using p value corrections, I may have been able to figure the rest out. I also had issues getting p values out of the function I was using for the Fisher’s LSD; the best I could get from it was grouping, which was helpful, but there were no hard numbers for me to go off of. I think an important detail here is that the authors were using GraphPad Prism, which automates and simplifies much of the analysis, meaning the authors may have simply not considered the minutiae of their statistical tests.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Warren, A.L., Lankri, D., Cunningham, M.J., Serrano, I.C., Parise, L.F., Kruegel, A.C., Duggan, P., Zilberg, G., Capper, M.J., Havel, V., Russo, S.J., Sames, F., &amp; Wacker, D. (2024). Structural pharmacology and therapeutic potential of 5-methoxytrypamines. <em>Nature, 630</em>, 237-246. https://doi.org/10.1038/s41586-024-07403-2</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>